=== aihua/ProfessionalJavaSecurityCode/Chapter10/com/isnetworks/crypto/database/SecureDriver_config.dtd
<!--
    Typical usage:

    <?xml version="1.0"?>

    <!DOCTYPE connectionServer SYSTEM "SecureDriver_config.dtd">

    <connectionServer>
    ...
    </connectionServer>
-->

  <!-- Root Element -->
  <!-- If no keystore is specified, the cacerts file is used-->
  <!ELEMENT connectionServer (dataSources,include?)>
  <!ATTLIST connectionServer
    id CDATA "SecureServer"
    keystore CDATA #IMPLIED
    authclient CDATA "true"
  >

  <!-- Datasource collection -->
  <!ELEMENT dataSources (dataSource)*>

  <!-- A datasource -->
  <!ELEMENT dataSource (driver,url,username?,password?,login*)>
  <!ATTLIST dataSource
    id CDATA #IMPLIED
    loginRequired CDATA "true"
  >

  <!-- The class -->
  <!ELEMENT driver (#PCDATA)>

  <!-- The url to the database -->
  <!ELEMENT url (#PCDATA)>

  <!-- The database username -->
  <!ELEMENT username (#PCDATA)>

  <!-- The database password -->
  <!ELEMENT password (#PCDATA)>

  <!-- Optional username and password requirements for datasource -->
  <!ELEMENT login (username, password)>

  <!-- Include content from another file -->
  <!ELEMENT include (#PCDATA)>

=== aihua/ProfessionalJavaSecurityCode/Chapter11/SecureDriver_config.xml
<?xml version="1.0"?>
<!DOCTYPE connectionServer SYSTEM "SecureDriver_config.dtd">
<connectionServer id="SecureDriver" keystore="trusted" authclient="true">
  

  <dataSources>
    <dataSource id="dataSource1" loginRequired="false">
      <driver>
        org.gjt.mm.mysql.Driver
      </driver>
      <url>
        jdbc:mysql://localhost/projava
      </url>
      <username>
        projava
      </username>
      <password>
        sasquatch
      </password>
      <login>
        <username>
          projava
        </username>
        <password>
          sasquatch
        </password>
      </login>
    </dataSource>
  </dataSources>

  <!-- Additional configuration info can be included here-->
  <include>
    /path/to/config
  </include>

</connectionServer>
